// src/components/ui/index.ts
export { default as Button } from "./button";
export { default as Input } from "./input";
export { default as Label } from "./label";
export { default as Select } from "./select";
export { default as SelectTrigger } from "./select-trigger";
export { default as SelectValue } from "./select-value";
export { default as SelectContent } from "./select-content";
export { default as SelectItem } from "./select-item";
export { default as Card } from "./card";
export { default as CardHeader } from "./card-header";
export { default as CardTitle } from "./card-title";
export { default as CardContent } from "./card-content";
export { default as CardDescription } from "./card-description";
export { default as Tabs } from "./tabs";
export { default as TabsList } from "./tabs-list";
export { default as TabsTrigger } from "./tabs-trigger";
export { default as TabsContent } from "./tabs-content";
export { default as Alert } from "./alert";
export { default as AlertDescription } from "./alert-description";
// ...add the rest using exact kebab-case filenames
